### PR TITLE
Some final 0.5.5 tweaks

### PR DESCRIPTION
**Pull request by slxdy**
@HookedBehemoth I made this PR based on your PR.
I've checked your solution, but it lacks a lot of features that were crucial to MelonEvents.
This solution should optimize all MelonEvents as it's not copying the actions array per invocation anymore.

I haven't tested it yet as I barely have any mods, so if you could check it for me @HookedBehemoth , I would appreciate it

### CODE REVIEW

**Comment by HookedBehemoth** [comment]
This would still allocate through param object[] and Invoke.
I can only check the numbers later.

**Comment by HookedBehemoth** [comment]
1x newarr per callback and then 3x per invocation afaict.
https://referencesource.microsoft.com/#mscorlib/system/reflection/methodinfo.cs,709

**Comment by slxdy** [comment]
> This would still allocate through param object[] and Invoke. I can only check the numbers later.

Well, if we're talking bout update methods, the array would be empty anyway, so it would just be an empty object

**Comment by HookedBehemoth** [comment]
And because it'll be an object, it will allocate.
I don't believe you can have a generic solution to this problem that doesn't allocate.
C# templates are just not versatile enough for that.
C++ variadic template argument expansion would be a great fit.
Edit: I don't mean to suggest adding C++ code for this. I only meant to point out the lack of versatility in C#

**Comment by slxdy** [comment]
> C++ variadic template argument expansion would be a great fit.

I don't think we need to go that far for a few extra nanoseconds

**Comment by HookedBehemoth** [comment]
This isn't purely about allocation time. Garbage collection causes big spikes.
Unnecessary allocations should be avoided. Especially if they are heavily fragmented like in this case.

**Comment by slxdy** [comment]
> Unnecessary allocations should be avoided. Especially if they are heavily fragmented like in this case.

The current system isnt as bad as it may look, in fact it's probably the same or faster than the invokation system in 0.5.4. It doesn't have to be perfect, as long as it doesn't cause any noticable performance issues for an average user

**Comment by slxdy** [comment]
@HookedBehemoth Alright, check if this is better

**Pull request merged**
