### PR TITLE
Added never_save option to MelonPreferences

### PR DESCRIPTION
**Pull request by yowchap**

### CODE REVIEW

**Comment by knah** [comment]
If it is never saved, what's the point of it? It would be just a property in mod code (potentially with custom setter to handle update events).

**Comment by yowchap** [comment]
> 
> 
> If it is never saved, what's the point of it? It would be just a property in mod code (potentially with custom setter to handle update events).

There's some context in #development-support but basically so you can have a pref that won't be written to MelonPreferences.cfg that a user has to put in manually.

**Comment by knah** [comment]
I might suggest implementing it as "don't save default value" then, instead of plain old never saving - a mod can choose whether or not it modifies a value, and "don't save default value" feels similar in purpose while being more flexible

**Comment by yowchap** [comment]
I'll look into changing to that once I've gotten my school work out of the way

**Comment by yowchap** [comment]
Now it'll save the pref to MelonPreferences.cfg as long as it's not the default value

**Pull request merged**
