### PR TITLE
allow overriding the deobfuscator remote API URL

### PR DESCRIPTION
**Pull request by HookedBehemoth**
Didn't actually test this yet since MelonLoader still doesn't crosscompile :)
I'll wait for the actions result.

The diff is fairly big but little was changed. Moved the loop content into a separate function with different indentation.

### CODE REVIEW

**Comment by RinLovesYou** [comment]
what does "MelonLoader doesn't crosscompile" mean?

Linux -> Windows? check out `cargo xwin` for the rust parts
Windows -> Linux? I don't see why it wouldn't

**Comment by HookedBehemoth** [comment]
Linux -> Windows
cargo xwin works for that, thanks!
The dotnet part still fails because Preload relies on ResGen
`/usr/share/dotnet/sdk/7.0.101/Microsoft.Common.CurrentVersion.targets(3312,5): error : ResGen.exe not supported on .NET Core MSBuild [~/source/MelonLoader/Dependencies/SupportModules/Preload/Preload.csproj]`
Can comment that out ofc

**Comment by RinLovesYou** [comment]
As for the actual implication of this patch, i don't see a great use case here. Are you maintaining deob maps for a game? Feel free to talk to us about adding it into the official api. 

I can sort of guess what you want to use this for, and i'm not sure that i can merge this in good faith because of that.

**Comment by HookedBehemoth** [comment]
I'm not maintaining it myself but I refuse to download non-free forks. Wanting to share binaries with my friends, it would be easier to just give them a config file instead of another dll.

**Comment by RinLovesYou** [comment]
Non free forks? I don't follow

**Comment by RinLovesYou** [comment]
Closing this as there has been significant inactivity, and motivations behind this seem dubious at best

**Pull request closed without merging**
