### PR TITLE
Make it permanent for real this time

### PR DESCRIPTION
**Pull request by RinLovesYou**
Electric Boogaloo

### CODE REVIEW

**Comment by RinLovesYou** [comment]
i just don't see why it's a launch option, more benefit to just always apply

**Comment by nitrog0d** [comment]
I'm pretty sure that's an option and not default because some games do things before it closes, terminating the process won't let it do that, like saving data, anyway terminating a process doesn't sound a good idea always
Also, why'd you only remove that part of the code? If you want to remove something do it entirely lol

**Comment by RinLovesYou** [comment]
Don't know what you mean by "that part"
I've seen the idea of implementing it permanently floating around and i didn't see any objections from devs when the subject was brought up

**Comment by slxdy** [comment]
Whats the problem with how it is rn tho? It's just a single config you can toggle, it doesn't take allot of effort.

**Comment by Slaynash** [comment]
Quitfix can cause some issues: The user not being properly disconnected, the game not being saved, ...

**Comment by slxdy** [comment]
Just close this request

**Comment by nitrog0d** [comment]
By "that part" I meant you're just removing a boolean check instead of removing the entire implementation like the config setting, the launch option on the bootstrap dll, references about it on README.md, idk what else but it doesn't really matter anyway

**Comment by Bluscream** [comment]
Yeah just close this request and lock it

**Pull request closed without merging**
