### PR TITLE
Proxy Modernization

### PR DESCRIPTION
**Pull request by nal532**
## Preface
Improved code-base for Melonloader's Proxy.

### Changes
* STL Naming Conventions
* Use std::filesystem to manage paths and directories
* Use std::filesystem::path instead of the previous weird string manipulation being done
* Removed unneeded memory allocations (new keyword, non-reference type arguments)
* Simplified code
* Use UNICODE instead of ASCII (when possible) when interacting with Win32 libraries
* No longer terminates non-Unity games, instead prevents further ML loading
* Utilizes constexpr when possible
* Switched Exports from a *"class"* to a namespace, more proper for it's purpose

### CODE REVIEW

**Comment by slxdy** [comment]
Ngl, I think this is something we really needed for a long time.

Just got one small suggestion
> No longer terminates non-Unity games, instead prevents further ML loading

There should also be at least some sort of a message box warning the user about the invalid ML installation

**Comment by slxdy** [comment]
Oh, and one more thing, you will probably need to redo the changes onto the alpha-development branch. The master branch is only used for displaying readme.md and for stable releases

**Comment by nal532** [comment]
> Oh, and one more thing, you will probably need to redo the changes onto the alpha-development branch. The master branch is only used for displaying readme.md and for stable releases

Ah, I'll make another PR on that branch.

> There should also be at least some sort of a message box warning the user about the invalid ML installation

I'll put this on the PR I make on the alpha branch.

**Comment by slxdy** [comment]
Neat

**Pull request closed without merging**
