### PR TITLE
fix Sigscan's bug

### PR DESCRIPTION
**Pull request by R0xdeadc0de**
QQ截图20220623170525
target:CC CC 4C 8D 0D 79 BB A2 07 4C 8D 05 D2 63 A3 07 48 8D 15 5B 63 A3 07 48 8D 0D C4 BA A2 07 E9 6F 1E 06 00 CC CC
sig:CC 4C 8D 0D ?? ?? ?? ?? 4C 8D 05 ?? ?? ?? ?? 48 8D 15 ?? ?? ?? ?? 48 8D 0D ?? ?? ?? ?? E9 ?? ?? ?? ?? CC
Sigscan will not be able to find the target.

### CODE REVIEW

**Comment by nitrog0d** [comment]
reminder this is genshin impact

**Comment by memetrollsXD** [comment]
reminder this is YuanShen (Genshin Impact CN version)

**Comment by memetrollsXD** [comment]
this pr changes nothing wtf 💀

**Comment by TheLostTree** [comment]
lol wdym nothing

**Comment by Taiga74164** [comment]
:KEKW:

**Comment by HerpDerpinstine** [comment]
Closing this under the guise that this would change nothing.
image

**Pull request closed without merging**
