### PR TITLE
Il2Cpp coroutine wrapper

### PR DESCRIPTION
**Pull request by HookedBehemoth**
Relies on this PR to the unhollower: https://github.com/knah/Il2CppAssemblyUnhollower/pull/71
Also sets hideflags to DontSave for support modules since coroutines qeued in OnApplicationStart were disposed by the destruction of the support module.

### CODE REVIEW

**Comment by HookedBehemoth** [comment]
Rebased to remove the SM_Components changes on the deleted files.

**Comment by HookedBehemoth** [comment]
The unhollower PR is merged now. Idk what happened here though @SamboyCoding 
Shall I clean this up again?

**Comment by HerpDerpinstine** [comment]
Go ahead and rebase.

**Comment by HookedBehemoth** [comment]
Unfucked it.
Should be ready for merge though I haven't tested it against upstream changes yet.

**Pull request merged**
