### PR TITLE
Proxy Modernization

### PR DESCRIPTION
**Pull request by nal532**
## Preface
Improved code-base for Melonloader's Proxy.
### Changes
* Upgraded toolset to MSVC v143
* STL Naming Conventions
* Use std::filesystem to manage paths and directories
* Use std::filesystem::path instead of the previous weird string manipulation being done
* Removed unneeded memory allocations (new keyword, non-reference type arguments)
* Simplified code
* Use UNICODE instead of ASCII (when possible) when interacting with Win32 libraries
* No longer terminates non-Unity games, instead prevents further ML loading
* Utilizes constexpr when possible
* Switched Exports from a "class" to a namespace, more proper for it's purpose

### CODE REVIEW

**Comment by SlidyDev** [comment]
sick

**Comment by nal532** [comment]
> sick

Regarding the error notification you recommended on the other PR, unfortunately we'll have to do without. Other libs loaded by the Game/Unity will also attempt to load version.dll. When opening a game, you'll get spammed with a couple errors when other libs load up version.dll, even though you are running a Unity game and the initial check when starting the process succeeded. I think it's best to keep it at a `return;` rather than displaying an error.

**Comment by HerpDerpinstine** [comment]
> > sick
> 
> Regarding the error notification you recommended on the other PR, unfortunately we'll have to do without. Other libs loaded by the Game/Unity will also attempt to load version.dll. When opening a game, you'll get spammed with a couple errors when other libs load up version.dll, even though you are running a Unity game and the initial check when starting the process succeeded. I think it's best to keep it at a `return;` rather than displaying an error.

The point of it is to kill any running process in the game's directory that isn't the game itself.
For example the UnityCrashHandler which uploads game logs and analytics.
A kill check is still necessary to keep users safe albeit probably needs some modification.

Also would like to mention that you removed the kill calls from the areas BEFORE the proxy loads its export redirects.
If the proxy fails before loading its export redirects they will just be calling null pointers and break anyways.
It's better to kill it right then and there when the proxy can't even be used normally.

**Comment by nal532** [comment]
> The point of it is to kill any running process in the game's directory that isn't the game itself.
For example the UnityCrashHandler which uploads game logs and analytics.
A kill check is still necessary to keep users safe albeit probably needs some modification.

Maybe it's worth checking the process name that's loading the proxy, like was done in a previous version inside DllMain. UnityCrashHandler(64)? Kill process. Anything else? Return.

> Also would like to mention that you removed the kill calls from the areas BEFORE the proxy loads its export redirects.
If the proxy fails before loading its export redirects they will just be calling null pointers and break anyways.
It's better to kill it right then and there when the proxy can't even be used normally.

I'm not sure what you mean by this. The code is as follows;
```c

	// @note: load original lib exports
	exports::load(index, originaldll);

	// @note: confirm we're loading into a unity game
	if (!is_unity(filepath))
		return; // (exports are already loaded, safe to return)

	if (strstr(GetCommandLineA(), "--no-mods") != nullptr)
		return; // (exports are already loaded, safe to return)
```
The proxy's exports are already loaded and at this point, it's 100% safe to return if needed.

Let me know what you think.

**Comment by HerpDerpinstine** [comment]
> > The point of it is to kill any running process in the game's directory that isn't the game itself.
> > For example the UnityCrashHandler which uploads game logs and analytics.
> > A kill check is still necessary to keep users safe albeit probably needs some modification.
> 
> Maybe it's worth checking the process name that's loading the proxy, like was done in a previous version inside DllMain. UnityCrashHandler(64)? Kill process. Anything else? Return.
> 
> > Also would like to mention that you removed the kill calls from the areas BEFORE the proxy loads its export redirects.
> > If the proxy fails before loading its export redirects they will just be calling null pointers and break anyways.
> > It's better to kill it right then and there when the proxy can't even be used normally.
> 
> I'm not sure what you mean by this. The code is as follows;
> 
> ```c
> 	// @note: load original lib exports
> 	exports::load(index, originaldll);
> 
> 	// @note: confirm we're loading into a unity game
> 	if (!is_unity(filepath))
> 		return; // (exports are already loaded, safe to return)
> 
> 	if (strstr(GetCommandLineA(), "--no-mods") != nullptr)
> 		return; // (exports are already loaded, safe to return)
> ```
> 
> The proxy's exports are already loaded and at this point, it's 100% safe to return if needed.
> 
> Let me know what you think.

Oh ok.
Let me look this over one more time but well done. 😄

**Pull request merged**
