### PR TITLE
TinyJSON: Fix polymorphic support and add nullable (T?) support

### PR DESCRIPTION
**Pull request by No3371**
# TinyJSON

## Fix polymorphic support
TinyJSON by design supports polymorphic fields with **type hint**. It seems like the [de-duplication attempt back in v0.2.3](https://github.com/LavaGang/MelonLoader/commit/e75f7241f93d7f70b2648d124aa64427bf29bc20#diff-616b8cbb488ac5b1dd4dd60d516dda3b6b220ba64dbdbe7994f4b37ecc7889b3L287) broke this feature. By copying the body of `DecodeFields` back into `DecodeType`, the feature starts working again.

As someone who doesn't understand enough to explain the issue, my assumption is `MethodInfo.MakeGenericMethod` does not cover inferred generic method calls inside the method body.

## [Nullable](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types) support
A conditional block is added to `DecodeType` to detect Nullable types. When decoding into T?, the method decodes the underlying type T instead, then cast it into T? and return.

### CODE REVIEW

**Comment by slxdy** [comment]
TinyJSON isn't really used anymore and will most likely be deprecated in the next patch. Users should use either System.Text.Json (on il2cpp) or Newtonsoft.Json (on mono)

**Comment by No3371** [comment]
> TinyJSON isn't really used anymore and will most likely be deprecated in the next patch. Users should use either System.Text.Json (on il2cpp) or Newtonsoft.Json (on mono)

I came from The Long Dark (IL2CPP) and I honestly suggest keep it as an alternative option, even only for the polymorphic feature.

The polymorphic support of `System.Text.Json` requires [annotating the base type](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism). Say, given an interface I, and implementation A and B. To support serializing and decoding A and B into a member of I, A and B must be referenced on I with a attribute from `System.Text.Json`.

As you may have noticed, it weirdly makes the base type depend on derived types.

This wouldn't be a problem only if we expects our projects are "closed" and do not interact with anything external. Yet, in modding scene, API/Framework mods exist, IMO we want stuff to be as open as possible.

This is why TinyJSON polymorphic feature is superior in modding scene. It simply uses Activator to create instances from **type hint**(Type.FullName). Any mod can freely derive types from other mods and serialize/deserialize their own types without issue.

**Comment by slxdy** [comment]
Isn't this already a thing with Newtonsoft Json?

**Comment by No3371** [comment]
Does Json.NET natively works in IL2CPP?

Either way I suddenly realized by
> TinyJSON isn't really used anymore

maybe you meant it's not used by ML anymore? In that case yeah I understand why it's going out.

I personally find it more pleasant to use and convenient as part of ML. But It's not like I can't just include TinyJSON in my projects or use it as a package.

**Comment by slxdy** [comment]
>maybe you meant it's not used by ML anymore?

Not sure if it ever was, but it isn't. Since Newtonsoft Json and System.Text.Json are the go-to packages (and are included with ML by default), there is no point in keeping an outdated package on this repo.

**Pull request merged**
